# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numque', models.IntegerField(verbose_name='numque')),
                ('numone', models.IntegerField(verbose_name='numone')),
                ('numtwo', models.IntegerField(verbose_name='numtwo')),
                ('lvl', models.IntegerField(verbose_name='lvl')),
            ],
        ),
    ]
